### ISSUE TITLE
Don't overwrite Char

### ISSUE THREAD

**Issue by phil294** [TamasSzekeres/x11-cr#15]
Hello,

https://github.com/TamasSzekeres/x11-cr/blob/2f83a3301e836efc7ebd437b8eccc33c59d0d3fd/src/x11/c/X.cr#L7

Could this be avoided? It pollutes the global type system when you `include X11`.

Otherwise, thanks for these bindings, they work great.

**Comment by TamasSzekeres** [comment]
Changed in release v1.1.0
