### ISSUE TITLE
Compile error when using X11::Display draw_points

### ISSUE THREAD

**Issue by JessicaInTime** [TamasSzekeres/x11-cr#6]
Hello, I'm trying out your library for learning how to make a software render, I'm also new to using Crystal so bare with me :sweat_smile: 

I was trying the draw_points method at `x11/display.cr:3549` and I'm getting a compile error for 2 things, 1 was a typo for the `points` param on line `3550:52`. After that, the compiler then complains on the `points` param for `X.draw_points`:

```crystal
In lib/x11/src/x11/display.cr:3550:41

 3550 | X.draw_points @dpy, d, gc, points.to_unsafe, points.size, mode
                                          ^--------
Error: argument 'points' of 'X11::C::X#draw_points' must be Pointer(X11::C::X::Point), not Pointer(X11::Point)
```

My example I was using (basically was using the example from the repo, but for brevity, I will just put the relevant code below):
```crystal
module Example
  include X11
  def self.main
    # irrelevant setup code

    test_points = Array(Point).new
    test_points << Point.new 3, 3
    test_points << Point.new 4, 4

    while true do
      if d.pending
        e = d.next_event
        case e
        when ExposeEvent
          d.draw_points w, d.default_gc(s), test_points, X11::C::CoordModeOrigin
        end
      end
    end
  end
end
```
---

Crystal version: 0.35.1
x11-cr version: master

**Comment by TamasSzekeres** [comment]
Fixed in release 1.0.0
