### ISSUE TITLE
Unable to call display.change_property

### ISSUE THREAD

**Issue by cmizzi** [TamasSzekeres/x11-cr#7]
Hello !

I am trying the library to implement a window manager. However, during my first implementation, the compiler blocks me with the following error : 

```
Showing last frame. Use --error-trace for full trace.

In lib/x11/src/x11/display.cr:2372:64

 2372 | X.change_property @dpy, w, property.to_u64, type.to_u64, format, mode, data.to_unsafe, data.size
                                                                 ^-----
Error: argument 'format' of 'X11::C::X#change_property' must be Int32, not (Int32 | Nil)
```

```crystal
require "x11"

module Example
  VERSION = "0.1.0"

  include X11

  def self.main
    d = Display.new
    data = Slice [
      d.intern_atom("_NET_SUPPORTED", false).to_i32!,
      d.intern_atom("_NET_WM_STATE", false).to_i32!,
      d.intern_atom("_NET_ACTIVE_WINDOW", false).to_i32!,
      d.intern_atom("_NET_WM_STATE_FULLSCREEN", false).to_i32!,
    ]

    d.change_property d.default_screen.root_window, d.intern_atom("_NET_SUPPORTED", false), Atom::Atom, PropModeReplace, data
  end

  main
end
```

I haven't been working with Crystal very long, so maybe I misunderstood something. But as a result, the indicated error is [thrown in here](https://github.com/TamasSzekeres/x11-cr/blob/master/src/x11/display.cr#L2372). 

https://github.com/TamasSzekeres/x11-cr/blob/e700f732a57d17e334188739b7be6b198328b7d9/src/x11/display.cr#L2366-L2373

I tried to debug the `data` variable and also tried to reimplement the `format` case and nowhere I noticed a `Int32 | Nil` union type.

---

When trying to debug a little more further, I tried something like this : 

```crystal
require "x11"

module Example
  include X11

  class Display < Display
    def change_property(w : X11::C::Window, property : Atom | X11::C::Atom, type : Atom | X11::C::Atom, mode : Int32, data : Bytes | Slice(Int16) | Slice(Int32)) : Int32 
      format = case data 
        when Bytes then 8 
        when Slice(Int16) then 16 
        when Slice(Int32) then 32 
      end 

      X.change_property @dpy, w, property.to_u64, type.to_u64, format.not_nil!, mode, data.to_unsafe, data.size 
    end 
  end

  def self.main
    d = Display.new
    a = Bytes [
      d.intern_atom("_NET_SUPPORTED", false),
      d.intern_atom("_NET_WM_STATE", false),
      d.intern_atom("_NET_ACTIVE_WINDOW", false),
      d.intern_atom("_NET_WM_STATE_FULLSCREEN", false),
    ]

    d.change_property d.default_screen.root_window, d.intern_atom("_NET_SUPPORTED", false), Atom::Atom, PropModeReplace, a
  end

  main
end
```

In fact, `format.not_nil!` seems to solve my issue.

But, on other hand, the definition of `change_property` seems wrong. The method attempts to see as data `Bytes | Slice(Int16) | Slice(Int32)` but the actual definition in C is declared with `PChar` (`PChar === UInt8*`). So if I try to put a `Slice(Int32)` as `data`, the compilation fails.

**Comment by TamasSzekeres** [comment]
Ok, thanks!

Fix in new release: 1.0.1
